NAME =		pulledpork
VERSION =	0.6.1
REV =		1

SOURCE =	https://pulledpork.googlecode.com/files/$(NAME)-$(VERSION).tar.gz

# RedHat/CentOS/Fedora dependencies.
EL_DEPS =	perl-libwww-perl \
		perl-Crypt-SSLEay \
		perl-Archive-Tar
FEDDORA_DEPS =	$(EL_DEPS)

include ../mk/build.mk
