#! /bin/sh
#
# Script to check for dependencies that should be provided by the
# system.

# Check for the existence of packages using rpm.
check_rpm() {
    missing=""
    for dep in $@; do
	echo -n "Checking for $dep: "
	if ! rpm -q $dep; then
	    missing="${missing} $dep"
	fi
    done

    if [[ "${missing}" ]]; then
	echo "Please install the following packages then try again:"
	echo "   ${missing}"
	exit 1
    fi
}

check_dpkg() {
    missing=""
    for dep in $@; do
	echo -n "Checking for package $dep: "
	if ! dpkg -s $dep > /dev/null 2>&1; then
	    echo "not found"
	    missing="${missing} $dep"
	else
	    echo "found"
	fi
    done
	
    if [ "${missing}" != "" ]; then
	echo "Please install the following packages then try again:"
	echo "    ${missing}"
	exit 1
    fi
}

case ${DIST_NAME} in
    el|fedora)
	check_rpm $@
	;;
    debian|ubuntu)
	check_dpkg $@
	;;
    *)
	echo "WARNING: Unable to check system dependencies on this platform: ${DIST_NAME}"
	;;
esac
