NAME =		libnetfilter_queue
VERSION =	1.0.0
REV =		1

SOURCE =	http://netfilter.org/projects/${NAME}/files/${NAME}-${VERSION}.tar.bz2

# System depends:
# libnfnetlink-devel
# kernel-headers
# autoconf
# automake
# libtool

include ../mk/build.mk
