NAME :=		barnyard2
VERSION :=	1.12
REV :=		1

SOURCE :=	https://github.com/firnsy/barnyard2/archive/v2-$(VERSION).tar.gz
SOURCE_FILE :=	$(NAME)-$(VERSION).tar.gz

OPTIONS :=	+mysql \
		+postgresql

WRKSRC =	$(WRKDIR)/$(NAME)-2-$(VERSION)

include ../mk/build.mk
