NAME :=		daemonlogger
VERSION :=	1.2.1
REV :=		1

SOURCE :=	http://www.snort.org/downloads/463
SOURCE_FILE :=	$(NAME)-$(VERSION).tar.gz

# System dependencies:
# libpcap-devel
# libdnet-devel

include ../mk/build.mk
