NAME :=		daq
VERSION :=	2.0.0
REV :=		1

SOURCE :=	http://www.snort.org/downloads/2266
SOURCE_FILE :=	$(NAME)-$(VERSION).tar.gz

# System dependencies, RHEL/Fedora naming for now.
#SYS_DEPENDS =	flex \
#		bison \
#		libpcap-devel

include ../mk/build.mk
