NAME :=		suricata
VERSION :=	1.3.6
REV :=		1

SOURCE :=	http://www.openinfosecfoundation.org/download/$(NAME)-$(VERSION).tar.gz

OPTIONS :=	+nfqueue

# System dependencies: 
# pcre-devel
# libyaml-devel
# file-devel (magic.h)
# zlib-devel

include ../mk/build.mk
